library(ZetaHTE)

n_checks <- 0L
check <- function(ok, label) {
  if (!isTRUE(ok)) stop("FAIL: ", label, call. = FALSE)
  n_checks <<- n_checks + 1L
  cat("PASS:", label, "\n")
}
same <- function(x, y, tol = 1e-10) isTRUE(all.equal(x, y, tolerance = tol, check.attributes = FALSE))
fails <- function(expr, pattern) {
  msg <- tryCatch({force(expr); ""}, error = function(e) conditionMessage(e))
  nzchar(msg) && grepl(pattern, msg, fixed = TRUE)
}
quiet <- function(expr) suppressWarnings(expr)

set.seed(120)
x <- rep(c(0, seq(0.1, 2, length.out = 9)), each = 12)
a <- rep(0:1, 60)
y <- stats::rnorm(120) + a * (0.5 + 2 * x)
fit <- quiet(zeta_test(y, a, x, B = 99, seed = 42, keep_bootstrap = TRUE))
check(inherits(fit, "zeta_test") && fit$status == "ok", "class and successful status")
check(nrow(fit$channels) == 3L && all(fit$channels$evaluable), "all three channels are returned")
check(all(is.finite(fit$channels$p_value)), "finite channel p values")
check(fit$p_global >= 0.01 && fit$p_global <= 1, "global p value bounds")
check(all(fit$channels$p_value >= 0.01 & fit$channels$p_value <= 1), "channel p value bounds")
check(abs(fit$p_global * 100 - round(fit$p_global * 100)) < 1e-12, "plus-one p value grid")
check(identical(dim(fit$bootstrap), c(99L, 3L)), "optional bootstrap matrix dimensions")
check(identical(fit$settings$scan_cuts, c(0.35, 0.5, 0.65)), "fixed paper scan locations")
check(identical(names(fit$combinations), c("combination", "statistic", "p_value")), "combination diagnostic contract")
check(!any(c("selected_component", "selected_channel") %in% names(fit)), "no hard Sparse or Dense signal classification")
check(all(fit$scan$lower_max < fit$scan$upper_min), "ties are not split between native-scale boundaries")
check(all(fit$data$u[fit$data$x == 0] == 0), "zero ranks are zero")
check(same(fit$data$u[x > 0], rank(x[x > 0]) / (sum(x > 0) + 1)), "average positive ranks")
check(is.null(quiet(zeta_test(y, a, x, B = 99, seed = 42))$bootstrap), "bootstrap matrix omitted by default")
again <- quiet(zeta_test(y, a, x, B = 99, seed = 42, keep_bootstrap = TRUE))
check(identical(fit$bootstrap, again$bootstrap), "fixed-seed reproducibility")
check(identical(fit$p_global, again$p_global), "fixed-seed p reproducibility")
set.seed(811)
previous <- .Random.seed
invisible(quiet(zeta_test(y, a, x, B = 39, seed = 42)))
check(identical(previous, .Random.seed), "explicit seed preserves caller RNG state")
invisible(quiet(zeta_test(y, a, x, B = 39)))
check(!identical(previous, .Random.seed), "NULL seed advances ordinary RNG stream")
rm(".Random.seed", envir = .GlobalEnv)
invisible(quiet(zeta_test(y, a, x, B = 39, seed = 42)))
check(!exists(".Random.seed", envir = .GlobalEnv, inherits = FALSE), "seeded call does not create persistent RNG state")

logfit <- quiet(zeta_test(y, a, log1p(x), B = 99, seed = 42))
check(same(fit$channels$statistic, logfit$channels$statistic), "monotone positive transformation preserves rank test")
check(identical(fit$p_global, logfit$p_global), "monotone transformation preserves global p")
affine <- quiet(zeta_test(2 * y + 3, a, x, B = 99, seed = 42))
check(same(fit$channels$statistic, affine$channels$statistic), "score scale invariance away from variance floor")
check(identical(fit$p_global, affine$p_global), "outcome affine transformation preserves p on fixture")

check(fails(zeta_test(y[-1], a, x), "same length"), "length mismatch rejected")
check(fails(zeta_test(y, factor(a), x), "plain numeric"), "factor treatment not silently recoded")
check(fails(zeta_test(y, a, matrix(x)), "plain numeric"), "matrix biomarker rejected")
check(fails(zeta_test(y, a + 1, x), "a must contain"), "1/2 treatment coding rejected")
check(fails(zeta_test(y, rep(0, 120), x), "a must contain"), "one treatment arm rejected")
check(fails(zeta_test(y, c(1, rep(0, 119)), x), "at least two"), "single treated subject rejected")
check(fails(zeta_test(y, a, -x), "nonnegative"), "negative biomarker rejected")
check(fails(zeta_test(y, a, x, outcome = "binary"), "coded 0/1"), "invalid binary outcome rejected")
check(fails(zeta_test(replace(y, 1, Inf), a, x), "Infinite"), "infinite outcome rejected")
check(fails(zeta_test(replace(y, 1, NA), a, x), "Missing"), "missing values fail by default")
check(fails(zeta_test(y, a, x, B = 1), "B must"), "single bootstrap draw rejected")
check(fails(zeta_test(y, a, x, B = 39.5), "B must"), "fractional B rejected")
check(fails(zeta_test(y, a, x, seed = -1), "seed must"), "negative seed rejected")
check(fails(zeta_test(y, a, x, zero_threshold = -1), "zero_threshold must"), "negative recode threshold rejected")
check(fails(zeta_test(y, a, x, keep_bootstrap = 1), "TRUE or FALSE"), "nonlogical flag rejected")
omitted <- quiet(zeta_test(replace(y, 1, NA), a, replace(x, 3, NA), B = 39,
                           seed = 42, na_action = "omit"))
check(identical(omitted$diagnostics$omitted_rows, c(1L, 3L)), "complete-row omission records original indices")
check(omitted$diagnostics$n_used == 118L, "complete-row omission counts")
manual <- quiet(zeta_test(y[-c(1, 3)], a[-c(1, 3)], x[-c(1, 3)], B = 39, seed = 42))
check(identical(omitted$p_global, manual$p_global), "omission equals explicit complete-case call")
recode <- quiet(zeta_test(y, a, x, B = 39, seed = 42, zero_threshold = 0.2))
x0 <- x
x0[x0 <= 0.2] <- 0
manual <- quiet(zeta_test(y, a, x0, B = 39, seed = 42))
check(identical(recode$p_global, manual$p_global), "prespecified zero recoding equals manual recoding")
check(identical(recode$data$x_original, as.numeric(x)), "original biomarker values retained")

allzero <- quiet(zeta_test(y, a, rep(0, 120), B = 39, seed = 42))
check(allzero$status == "not_evaluable" && is.na(allzero$p_global), "all-zero biomarker is NA, not p=1")
constant <- quiet(zeta_test(rep(1, 120), a, x, B = 39, seed = 42))
check(constant$status == "not_evaluable" && is.na(constant$p_global), "constant outcome is explicitly unavailable")
nozero <- quiet(zeta_test(y, a, seq_len(120), B = 39, seed = 42))
check(nozero$status == "ok" && !nozero$channels$evaluable[1] &&
        all(nozero$channels$evaluable[-1]), "no-zero case uses tail channels with explicit missing Jump")
fewpos <- quiet(zeta_test(y, a, c(rep(0, 113), 1:7), B = 39, seed = 42))
check(fewpos$status == "not_evaluable", "too few positives explicitly unavailable")
jump_only <- quiet(zeta_test(y, a, rep(c(0, 1), each = 60), B = 39, seed = 42))
check(jump_only$status == "ok" && identical(jump_only$channels$evaluable, c(TRUE, FALSE, FALSE)),
      "constant positive tail retains only Jump")
check(all(nzchar(jump_only$channels$reason[-1])), "missing-channel reasons supplied")
check(fails(zeta_interpret(allzero), "not evaluable"), "interpretation rejects unevaluable test")

gate <- fit
gate$p_global <- 0.4
check(fails(zeta_interpret(gate), "exceeds alpha"), "nonsignificant default gate")
ex <- quiet(zeta_interpret(gate, allow_nonsignificant = TRUE))
check(!ex$global_significant, "explicit override remains marked nonsignificant")
gate$p_global <- 0.05
check(zeta_interpret(gate)$global_significant, "inclusive alpha boundary")
check(fails(zeta_interpret(fit, alpha = 0), "alpha must"), "invalid alpha rejected")
check(fails(zeta_interpret(fit, cutoff = 0), "cutoff must"), "zero not accepted as positive-tail cutoff")
check(fails(zeta_interpret(fit, cutoff_inclusive = "guess"), "arg"), "ambiguous cutoff rule rejected")
ex <- quiet(zeta_interpret(fit, allow_nonsignificant = TRUE))
tau <- function(idx) mean(y[idx & a == 1]) - mean(y[idx & a == 0])
check(same(ex$effects$estimate[1], tau(x == 0) - tau(x > 0)), "Jump contrast sign and direct means")
dd <- fit$data[x > 0, ]
slope <- stats::coef(stats::lm(y ~ a * u, data = dd))[["a:u"]]
check(same(ex$effects$estimate[2], slope), "Tail linear slope equals independent regression")
cstar <- fit$scan$rank_cutoff[which.max(fit$scan$statistic)]
check(identical(ex$selected_scan$rank_cutoff, cstar), "selected location maximizes observed step score")
check(same(ex$effects$estimate[3], tau(x > 0 & fit$data$u > cstar) -
             tau(x > 0 & fit$data$u <= cstar)), "step contrast excludes zeros and uses upper minus lower")
cutoff <- x[61]
low_eq <- quiet(zeta_interpret(fit, cutoff = cutoff, allow_nonsignificant = TRUE))
high_eq <- quiet(zeta_interpret(fit, cutoff = cutoff, cutoff_inclusive = "upper", allow_nonsignificant = TRUE))
check(same(low_eq$effects$estimate[4], tau(x > cutoff) - tau(x > 0 & x <= cutoff)), "user cutoff lower equality convention")
check(same(high_eq$effects$estimate[4], tau(x >= cutoff) - tau(x > 0 & x < cutoff)), "user cutoff upper equality convention")
check(identical(low_eq$p_global, high_eq$p_global) && identical(fit$p_global, low_eq$p_global), "user cutoff does not change global test")
check(identical(low_eq$selected_scan, high_eq$selected_scan), "user cutoff does not replace internal scan")
outside <- quiet(zeta_interpret(fit, cutoff = 100, allow_nonsignificant = TRUE))
check(is.na(outside$effects$estimate[4]) && nzchar(outside$effects$reason[4]), "empty user-cutoff group produces NA with reason")

set.seed(61)
yb <- stats::rbinom(120, 1, 0.15 + 0.6 * a * x / max(x))
binary <- quiet(zeta_test(yb, a, x, outcome = "binary", B = 99, seed = 42))
check(binary$status == "ok", "binary outcome test executes")
biex <- quiet(zeta_interpret(binary, allow_nonsignificant = TRUE))
check(biex$effects$scale[1] == "risk difference", "binary scale label")
check(same(biex$groups$effect, biex$groups$mean_treatment - biex$groups$mean_control), "binary subgroup risk differences")
check(all(abs(biex$groups$effect) <= 1), "risk differences remain in probability units")
check(is.null(summary(fit)$data) && is.null(summary(fit)$bootstrap), "summary omits individual records and bootstrap matrix")
check(any(grepl("Global p value", capture.output(print(fit)), fixed = TRUE)), "test print method")
check(any(grepl("Combination diagnostics", capture.output(summary(fit)), fixed = TRUE)), "summary print method")
check(any(grepl("Exploratory", capture.output(print(ex)), fixed = TRUE)), "interpretation print method")
fmt <- getFromNamespace("format_zeta_number", "ZetaHTE")
check(identical(fmt(c(0.2, 0.05)), c("0.2", "0.05")), "display omits padded trailing zeros")
upper <- getFromNamespace("self_upper_p", "ZetaHTE")
check(same(upper(c(2, 2, 5)), c(1, 1, 0.5)), "inclusive self-reference with ties")
ds <- getFromNamespace("direction_score", "ZetaHTE")
r <- c(-2, -1, 1, 2)
cc <- matrix(c(1, -1, -1, 1), ncol = 1)
check(same(ds(r, cc), (sum(r * cc) / sqrt(4))^2 / max(stats::var(as.numeric(r * cc)), 1e-8)),
      "score matches explicit scalar formula")
cat("\nTOTAL CHECKS:", n_checks, "\n")
